---
# Build and Test AIDE Database
# Identifier: (ssg:rhel8|cis_server_l1|xccdf_org.ssgproject.content_rule_aide_build_database,fix)
# Version: undefined
# platform = multi_platform_all
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: Build and Test AIDE Database
  hosts: all
  become: true
  tags:
    - CCE-80675-2
    - CJIS-5.10.1.3
    - DISA-STIG-RHEL-08-010359
    - NIST-800-53-CM-6(a)
    - PCI-DSS-Req-11.5
    - PCI-DSSv4-11.5.2
    - aide_build_database
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - restrict_strategy
  vars:
    insights_signature_exclude: /hosts,/vars/insights_signature
    insights_signature: !!binary |
      TFMwdExTMUNSVWRKVGlCUVIxQWdVMGxIVGtGVVZWSkZMUzB0TFMwS1ZtVnljMmx2YmpvZ1IyNTFV
      RWNnZGpFS0NtbFJTV05DUVVGQ1EwRkJSMEpSU20xNGNHSm9RVUZ2U2tWTmRuYzFPRVFyYWpWd1Rt
      cGFiMUZCU2xoVmVHOUZaWE54ZFZJeVVUa3pWMEZsWXpWV09IQUtaR3AyZURGRkx6RlhjazFxV2tK
      NGVVaDRZVTFzUXpnMVRtVmtUVWx5VjJsdldVaGhjWGR6YXpWTk9GUTVVa0Z5TlVkalRVODFjVUY0
      YVVwWmJtTmtaZ3BSZHpkNEswNU1XRlZIU0hWR09YUkZNakpJU0c5TE5tTkxjREJpSzJWeE4wVlBU
      VkZhWlRabVYyUjNlSGg0TTJ0dmVYRjFhVXhwYWpaM2FWWnRRbGRvQ2xCRmVFeHljM1EyWnpka1Rp
      OTJiell6WnpNeFRuTlhlR05ZTjFwR1NteG5VWEZzTVZVM1dFRmpVREZZT0daV05qUXlNa2xWZEhG
      WGNVWm9hRGR1VlRnS1drOXRkbG94Tm1sMVVsUlhNekZ2TVd4NVpVSjRSRGhQWjB0a2RFUTFjMlE0
      YVZsMFExTjRlVFJQVVhoSVV5c3lkMVJrZDIwNU1WSjNRMDE1VUVwMWJ3cFZaRTlZVGpWeFVGaHZi
      M0FyVGxBMVZ6Rk9VMGx0TjFkUE9HaHZVek5hVVVrMFJqZzRhbWMzTDJkb2VIcHRlR1Z1T0hnMFlX
      eERTVXh3ZW5nd1VtaHpDa3M0WW5sWldraDBkbTF3UVdKS1QyVTVlV0ZTZDBwSU1uWjNZMlJ1U0Vw
      RU9IaFZOVE41VEhGR1ZHTnZiQ3RSVW10VE1FdFVZM0ZsUjBsRGMyc3laV2tLUkVGUFpYUkhSbTVU
      TjNwWk5YVlZTblZVVVVKbk5sTXhjRkJ2Y200MWVWVmFUVXh0ZG1WQ2VuWmpiVEpWY3paS2MydHlZ
      blZzTnpNeVpGSmpXVkF5THdwa05XRXdaRkVyTW05V1MyUjJVM1YyU1c1WFRXTjRaMFV4TVc5RlJ6
      UnZkWEIwVGtOR1Z6Wm9VWGhwTjFNNGJsQklNVkoyYlVJNWQxa3pZMVJIWWpFNUNtVkxkSGh1ZGpo
      YVRFMVFWMlpoUkc5MWR6TlNWbVp3VjJWd2RITkhRME5pZVhwT1JVOVpOVlZ4Yldob2NVeEdOWEJa
      ZFZOeWVtc3ZLMnBYZEZOeFQwWUtZV1pHVDFoWWRrbENXRmRRVUN0NFFYVnlVVnA0ZFRGTmRrTkRj
      a2R2V25CcGJGQlZZME5HWXpodllscEJjRWRIYlhrM2FVTTBkR05VVTJOelVYUlRWUXBVT0V4ckwx
      cG5WRVJrWVZKbVdXWlBTRmRyU1FvOVMyZFBUQW90TFMwdExVVk9SQ0JRUjFBZ1UwbEhUa0ZVVlZK
      RkxTMHRMUzBL
  tasks:

    - name: Build and Test AIDE Database - Ensure AIDE Is Installed
      ansible.builtin.package:
        name: '{{ item }}'
        state: present
      with_items:
        - aide
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman", "container"]

    - name: Build and Test AIDE Database - Build and Test AIDE Database
      ansible.builtin.command: /usr/sbin/aide --init
      changed_when: true
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman", "container"]

    - name: Build and Test AIDE Database - Check Whether the Stock AIDE Database Exists
      ansible.builtin.stat:
        path: /var/lib/aide/aide.db.new.gz
      register: aide_database_stat
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman", "container"]

    - name: Build and Test AIDE Database - Stage AIDE Database
      ansible.builtin.copy:
        src: /var/lib/aide/aide.db.new.gz
        dest: /var/lib/aide/aide.db.gz
        backup: true
        remote_src: true
      when:
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman", "container"]
        - (aide_database_stat.stat.exists is defined and aide_database_stat.stat.exists)